// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFnQs2gBKh2MzZaSMmPBHERPAKsJaI-mc',
    appId: '1:261949847818:web:6ea6ede73dad5a3fbca2f3',
    messagingSenderId: '261949847818',
    projectId: 'cw07-b249d',
    authDomain: 'cw07-b249d.firebaseapp.com',
    storageBucket: 'cw07-b249d.firebasestorage.app',
    measurementId: 'G-XR6012GTWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA77ndPj2WWRwBROeJUtWfmMTsspIn0S2I',
    appId: '1:261949847818:android:ab7f00e33ab95189bca2f3',
    messagingSenderId: '261949847818',
    projectId: 'cw07-b249d',
    storageBucket: 'cw07-b249d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqavhCwUiVddHsj4EnhA7zi7hNgTI3baw',
    appId: '1:261949847818:ios:cf1246c4ceb2d91abca2f3',
    messagingSenderId: '261949847818',
    projectId: 'cw07-b249d',
    storageBucket: 'cw07-b249d.firebasestorage.app',
    iosBundleId: 'com.example.cw07',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqavhCwUiVddHsj4EnhA7zi7hNgTI3baw',
    appId: '1:261949847818:ios:cf1246c4ceb2d91abca2f3',
    messagingSenderId: '261949847818',
    projectId: 'cw07-b249d',
    storageBucket: 'cw07-b249d.firebasestorage.app',
    iosBundleId: 'com.example.cw07',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFnQs2gBKh2MzZaSMmPBHERPAKsJaI-mc',
    appId: '1:261949847818:web:24eaaa9b09838f0fbca2f3',
    messagingSenderId: '261949847818',
    projectId: 'cw07-b249d',
    authDomain: 'cw07-b249d.firebaseapp.com',
    storageBucket: 'cw07-b249d.firebasestorage.app',
    measurementId: 'G-KPS8FJJVNV',
  );
}
